# Generated by Django 4.2.2 on 2024-05-16 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlogRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='название')),
                ('slug', models.CharField(blank=True, max_length=150, null=True, verbose_name='slug')),
                ('body', models.TextField(blank=True, null=True, verbose_name='содержимое')),
                ('picture', models.ImageField(blank=True, null=True, upload_to='bloglpictures', verbose_name='фото')),
                ('published_at', models.DateField(blank=True, null=True, verbose_name='дата публикации')),
                ('is_published', models.BooleanField(default=False, verbose_name='опубликовано')),
                ('view_count', models.IntegerField(default=0, verbose_name='количество просмотров')),
            ],
            options={
                'verbose_name': 'запись',
                'verbose_name_plural': 'записи',
                'ordering': ['published_at'],
            },
        ),
    ]
