# Generated by Django 5.0.3 on 2024-04-02 08:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='название сообщения')),
                ('body', models.TextField(verbose_name='текст сообщения')),
            ],
        ),
        migrations.CreateModel(
            name='Period',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='периодичность')),
                ('hour', models.IntegerField(verbose_name='часы')),
                ('day', models.IntegerField(verbose_name='минуты')),
                ('week', models.IntegerField(verbose_name='недели')),
            ],
        ),
        migrations.CreateModel(
            name='Sending',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='название рассылки')),
                ('start_time', models.DateTimeField(verbose_name='время начала')),
                ('end_time', models.DateTimeField(verbose_name='время завершения')),
                ('message', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='main.message', verbose_name='содержание рассылки')),
                ('period', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='main.period', verbose_name='периодичность рассылки')),
            ],
            options={
                'verbose_name': 'рассылка',
                'verbose_name_plural': 'рассылки',
            },
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='имя')),
                ('surname', models.CharField(max_length=50, verbose_name='фамилия')),
                ('email', models.EmailField(max_length=254, verbose_name='почта')),
                ('sending', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.sending', verbose_name='рассылка')),
            ],
        ),
    ]
