# Generated by Django 5.0.3 on 2024-04-04 06:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_mailingattempt_alter_message_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='message',
            options={'ordering': ('name',), 'verbose_name': 'сообщение', 'verbose_name_plural': 'сообщения'},
        ),
        migrations.AlterField(
            model_name='sending',
            name='end_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='время завершения'),
        ),
        migrations.AlterField(
            model_name='sending',
            name='message',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='main.message', verbose_name='содержание рассылки'),
        ),
    ]
