# Generated by Django 5.0.3 on 2024-04-04 13:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_message_options_alter_sending_end_time_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='client',
            options={'verbose_name': 'клиент', 'verbose_name_plural': 'клиенты'},
        ),
        migrations.AlterModelOptions(
            name='message',
            options={'ordering': ('name',), 'verbose_name': 'сообщение для рассылки', 'verbose_name_plural': 'сообщения для рассылки'},
        ),
        migrations.AlterModelOptions(
            name='period',
            options={'verbose_name': 'периодичность'},
        ),
        migrations.RemoveField(
            model_name='period',
            name='day',
        ),
        migrations.RemoveField(
            model_name='period',
            name='hour',
        ),
        migrations.RemoveField(
            model_name='period',
            name='week',
        ),
        migrations.AddField(
            model_name='period',
            name='days',
            field=models.IntegerField(default=0, verbose_name='дни'),
        ),
        migrations.AddField(
            model_name='period',
            name='hours',
            field=models.IntegerField(default=0, verbose_name='часы'),
        ),
        migrations.AddField(
            model_name='period',
            name='minutes',
            field=models.IntegerField(default=0, verbose_name='минуты'),
        ),
        migrations.AddField(
            model_name='period',
            name='weeks',
            field=models.IntegerField(default=0, verbose_name='недели'),
        ),
        migrations.AlterField(
            model_name='message',
            name='body',
            field=models.TextField(verbose_name='текст сообщения для рассылки'),
        ),
        migrations.AlterField(
            model_name='message',
            name='name',
            field=models.CharField(max_length=50, verbose_name='тема сообщения для рассылки'),
        ),
        migrations.AlterField(
            model_name='period',
            name='name',
            field=models.CharField(max_length=50, verbose_name='периодичность рассылки сообщения'),
        ),
        migrations.AlterField(
            model_name='sending',
            name='period',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='main.period', verbose_name='периодичность рассылки'),
        ),
    ]
