# Generated by Django 5.0.3 on 2024-04-04 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_period_options_alter_sending_period'),
    ]

    operations = [
        migrations.AddField(
            model_name='sending',
            name='status',
            field=models.CharField(choices=[('en', 'Завершена'), ('cr', 'Создана'), ('st', 'Запущена')], default='cr', max_length=2),
        ),
    ]
