# Generated by Django 5.0.3 on 2024-04-05 08:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_sending_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sending',
            name='period',
            field=models.CharField(choices=[('1D', 'раз в день'), ('1W', 'раз в неделю'), ('1M', 'раз в месяц')], max_length=2, verbose_name='периодичность рассылки'),
        ),
        migrations.AlterModelOptions(
            name='mailingattempt',
            options={'ordering': ('latest_att_time',), 'verbose_name': 'попытка рассылки', 'verbose_name_plural': 'попытки рассылки'},
        ),
        migrations.AlterModelOptions(
            name='sending',
            options={'ordering': ('start_time',), 'verbose_name': 'рассылка', 'verbose_name_plural': 'рассылки'},
        ),
        migrations.RemoveField(
            model_name='sending',
            name='attempt',
        ),
        migrations.AddField(
            model_name='mailingattempt',
            name='sending',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.sending', verbose_name='related sending'),
        ),
        migrations.AddField(
            model_name='sending',
            name='last_ok_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='дата последней удачной рассылки'),
        ),
        migrations.AlterField(
            model_name='client',
            name='email',
            field=models.EmailField(default='scroco@mail.ru', max_length=254, verbose_name='почта'),
        ),
        migrations.AlterField(
            model_name='client',
            name='surname',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='фамилия'),
        ),
        migrations.AlterField(
            model_name='mailingattempt',
            name='status',
            field=models.BooleanField(default=False, verbose_name='статус последней попытки'),
        ),
        migrations.DeleteModel(
            name='Period',
        ),
    ]
